class OmskAlkomarkets < ActiveRecord::Migration
  def change
    Point.new(:user => User.find_by_name('Влажная Ватрушка'),:lat =>"73.315657",  :lng => "54.985305", :point_type => "shop", :name => "Алкоголь 24 часа, сеть продовольственных магазинов", :description => "Сетевой магазин. 24 часа." ).save
    Point.new(:user => User.find_by_name('Влажная Ватрушка'),:lat =>"73.255034",  :lng => "55.031359", :point_type => "shop", :name => "Алкоголь 24 часа, сеть продовольственных магазинов", :description => "Сетевой магазин. 24 часа." ).save
    Point.new(:user => User.find_by_name('Влажная Ватрушка'),:lat =>"73.312942",  :lng => "54.982326", :point_type => "shop", :name => "Алкоголь 24 часа, сеть продовольственных магазинов", :description => "Сетевой магазин. 24 часа." ).save
    Point.new(:user => User.find_by_name('Влажная Ватрушка'),:lat =>"73.303356",  :lng => "54.990044", :point_type => "shop", :name => "Алкоголь 24 часа, сеть продовольственных магазинов", :description => "Сетевой магазин. 24 часа." ).save
    Point.new(:user => User.find_by_name('Влажная Ватрушка'),:lat =>"73.411408",  :lng => "54.9728", :point_type => "shop", :name => "Алкоголь 24 часа, сеть продовольственных магазинов", :description => "Сетевой магазин. 24 часа." ).save
    Point.new(:user => User.find_by_name('Влажная Ватрушка'),:lat =>"73.354133",  :lng => "54.998634", :point_type => "shop", :name => "Алкоголь 24 часа, сеть продовольственных магазинов", :description => "Сетевой магазин. 24 часа." ).save
    Point.new(:user => User.find_by_name('Влажная Ватрушка'),:lat =>"73.313172",  :lng => "54.942345", :point_type => "shop", :name => "Алкоголь 24 часа, сеть продовольственных магазинов", :description => "Сетевой магазин. 24 часа." ).save
    Point.new(:user => User.find_by_name('Влажная Ватрушка'),:lat =>"73.416614",  :lng => "54.990864", :point_type => "shop", :name => "Алкоголь 24 часа, сеть продовольственных магазинов", :description => "Сетевой магазин. 24 часа." ).save
    Point.new(:user => User.find_by_name('Влажная Ватрушка'),:lat =>"73.400404",  :lng => "54.990624", :point_type => "shop", :name => "Алкоголь 24 часа, сеть продовольственных магазинов", :description => "Сетевой магазин. 24 часа." ).save
    Point.new(:user => User.find_by_name('Влажная Ватрушка'),:lat =>"73.295948",  :lng => "54.999107", :point_type => "shop", :name => "Алкоголь 24 часа, сеть продовольственных магазинов", :description => "Сетевой магазин. 24 часа." ).save
    Point.new(:user => User.find_by_name('Влажная Ватрушка'),:lat =>"73.305626",  :lng => "55.046514", :point_type => "shop", :name => "Алкоголь 24 часа, сеть продовольственных магазинов", :description => "Сетевой магазин. 24 часа." ).save
    Point.new(:user => User.find_by_name('Влажная Ватрушка'),:lat =>"73.270701",  :lng => "55.035708", :point_type => "shop", :name => "Алкоголь 24 часа, сеть продовольственных магазинов", :description => "Сетевой магазин. 24 часа." ).save
    Point.new(:user => User.find_by_name('Влажная Ватрушка'),:lat =>"73.378323",  :lng => "55.030199", :point_type => "shop", :name => "Алкоголь 24 часа, сеть продовольственных магазинов", :description => "Сетевой магазин. 24 часа." ).save
    Point.new(:user => User.find_by_name('Влажная Ватрушка'),:lat =>"73.262892",  :lng => "55.041116", :point_type => "shop", :name => "Алкоголь 24 часа, сеть продовольственных магазинов", :description => "Сетевой магазин. 24 часа." ).save
    Point.new(:user => User.find_by_name('Влажная Ватрушка'),:lat =>"73.389697",  :lng => "54.94084", :point_type => "shop", :name => "Алкоголь 24 часа, сеть продовольственных магазинов", :description => "Сетевой магазин. 24 часа." ).save
    Point.new(:user => User.find_by_name('Влажная Ватрушка'),:lat =>"73.440196",  :lng => "54.942831", :point_type => "shop", :name => "Алкоголь 24 часа, сеть продовольственных магазинов", :description => "Сетевой магазин. 24 часа." ).save
    Point.new(:user => User.find_by_name('Влажная Ватрушка'),:lat =>"73.444189",  :lng => "54.961663", :point_type => "shop", :name => "Алкоголь 24 часа, сеть продовольственных магазинов", :description => "Сетевой магазин. 24 часа." ).save
    Point.new(:user => User.find_by_name('Влажная Ватрушка'),:lat =>"73.218931",  :lng => "55.03332", :point_type => "shop", :name => "Алкоголь 24 часа, сеть продовольственных магазинов", :description => "Сетевой магазин. 24 часа." ).save
    Point.new(:user => User.find_by_name('Влажная Ватрушка'),:lat =>"73.455394",  :lng => "54.915539", :point_type => "shop", :name => "Алкоголь 24 часа, сеть продовольственных магазинов", :description => "Сетевой магазин. 24 часа." ).save
    Point.new(:user => User.find_by_name('Влажная Ватрушка'),:lat =>"73.465871",  :lng => "54.92583", :point_type => "shop", :name => "Алкоголь 24 часа, сеть продовольственных магазинов", :description => "Сетевой магазин. 24 часа." ).save
    Point.new(:user => User.find_by_name('Влажная Ватрушка'),:lat =>"73.508336",  :lng => "54.934125", :point_type => "shop", :name => "Алкоголь 24 часа, сеть продовольственных магазинов", :description => "Сетевой магазин. 24 часа." ).save
  end
end
