require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ChatMessagesController do

  # This should return the minimal set of attributes required to create a valid
  # ChatMessage. As you add validations to ChatMessage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ChatMessagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all chat_messages as @chat_messages" do
      chat_message = ChatMessage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:chat_messages).should eq([chat_message])
    end
  end

  describe "GET show" do
    it "assigns the requested chat_message as @chat_message" do
      chat_message = ChatMessage.create! valid_attributes
      get :show, {:id => chat_message.to_param}, valid_session
      assigns(:chat_message).should eq(chat_message)
    end
  end

  describe "GET new" do
    it "assigns a new chat_message as @chat_message" do
      get :new, {}, valid_session
      assigns(:chat_message).should be_a_new(ChatMessage)
    end
  end

  describe "GET edit" do
    it "assigns the requested chat_message as @chat_message" do
      chat_message = ChatMessage.create! valid_attributes
      get :edit, {:id => chat_message.to_param}, valid_session
      assigns(:chat_message).should eq(chat_message)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ChatMessage" do
        expect {
          post :create, {:chat_message => valid_attributes}, valid_session
        }.to change(ChatMessage, :count).by(1)
      end

      it "assigns a newly created chat_message as @chat_message" do
        post :create, {:chat_message => valid_attributes}, valid_session
        assigns(:chat_message).should be_a(ChatMessage)
        assigns(:chat_message).should be_persisted
      end

      it "redirects to the created chat_message" do
        post :create, {:chat_message => valid_attributes}, valid_session
        response.should redirect_to(ChatMessage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved chat_message as @chat_message" do
        # Trigger the behavior that occurs when invalid params are submitted
        ChatMessage.any_instance.stub(:save).and_return(false)
        post :create, {:chat_message => {  }}, valid_session
        assigns(:chat_message).should be_a_new(ChatMessage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ChatMessage.any_instance.stub(:save).and_return(false)
        post :create, {:chat_message => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested chat_message" do
        chat_message = ChatMessage.create! valid_attributes
        # Assuming there are no other chat_messages in the database, this
        # specifies that the ChatMessage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ChatMessage.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => chat_message.to_param, :chat_message => { "these" => "params" }}, valid_session
      end

      it "assigns the requested chat_message as @chat_message" do
        chat_message = ChatMessage.create! valid_attributes
        put :update, {:id => chat_message.to_param, :chat_message => valid_attributes}, valid_session
        assigns(:chat_message).should eq(chat_message)
      end

      it "redirects to the chat_message" do
        chat_message = ChatMessage.create! valid_attributes
        put :update, {:id => chat_message.to_param, :chat_message => valid_attributes}, valid_session
        response.should redirect_to(chat_message)
      end
    end

    describe "with invalid params" do
      it "assigns the chat_message as @chat_message" do
        chat_message = ChatMessage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ChatMessage.any_instance.stub(:save).and_return(false)
        put :update, {:id => chat_message.to_param, :chat_message => {  }}, valid_session
        assigns(:chat_message).should eq(chat_message)
      end

      it "re-renders the 'edit' template" do
        chat_message = ChatMessage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ChatMessage.any_instance.stub(:save).and_return(false)
        put :update, {:id => chat_message.to_param, :chat_message => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested chat_message" do
      chat_message = ChatMessage.create! valid_attributes
      expect {
        delete :destroy, {:id => chat_message.to_param}, valid_session
      }.to change(ChatMessage, :count).by(-1)
    end

    it "redirects to the chat_messages list" do
      chat_message = ChatMessage.create! valid_attributes
      delete :destroy, {:id => chat_message.to_param}, valid_session
      response.should redirect_to(chat_messages_url)
    end
  end

end
